version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-docker-talki-app
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: npm run serve

  eslint:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    entrypoint:
      ['sh', '-c', 'npm install --legacy-peer-deps && npx eslint --fix .']

  prettier:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    entrypoint:
      ['sh', '-c', 'npm install --legacy-peer-deps && npx prettier --write .']

  watcher:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - .:/app
    entrypoint:
      [
        'sh',
        '-c',
        'npm install --legacy-peer-deps && npx chokidar "**/*.js" "**/*.vue" -c "npx prettier --write {path} && npx eslint --fix {path}"',
      ]
