version: '3'
services:
  vue-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: vue-docker-talki-app
    ports:
      - '8080:8080'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - WATCHPACK_POLLING=true
      - NODE_ENV=development
    stdin_open: true
    tty: true
    command: npm run serve
